SELECT CASE
WHEN GRADES.GRADE>=8 THEN STUDENTS.NAME
ELSE NULL
END,GRADES.GRADE,STUDENTS.MARKS
FROM STUDENTS,GRADES 
WHERE STUDENTS.MARKS>=GRADES.MIN_MARK AND STUDENTS.MARKS<=GRADES.MAX_MARK
ORDER BY GRADES.GRADE DESC, STUDENTS.NAME, STUDENTS.MARKS;